# Generated by Django 6.0.6 on 2026-06-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, verbose_name='挡位名称')),
                ('min_value', models.IntegerField(default=0, verbose_name='最小功率(W)')),
                ('max_value', models.IntegerField(help_text='0 表示无上限', verbose_name='最大功率(W)')),
            ],
            options={
                'verbose_name': '功率挡位',
                'verbose_name_plural': '功率挡位',
                'ordering': ['min_value'],
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='协议名称')),
            ],
            options={
                'verbose_name': '快充协议',
                'verbose_name_plural': '快充协议',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('充电器', '充电器'), ('充电宝', '充电宝')], max_length=10, verbose_name='类别')),
                ('brand', models.CharField(max_length=50, verbose_name='品牌')),
                ('name', models.CharField(max_length=100, verbose_name='型号名称')),
                ('max_power', models.IntegerField(verbose_name='最高总功率(W)')),
                ('max_single_power', models.IntegerField(verbose_name='单口最高功率(W)')),
                ('ports_desc', models.CharField(max_length=20, verbose_name='接口描述')),
                ('port_count', models.IntegerField(default=1, verbose_name='接口数量')),
                ('has_usb_a', models.BooleanField(default=False, verbose_name='是否带USB-A口')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='参考价格')),
                ('image', models.ImageField(upload_to='products/', verbose_name='产品图片')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='重量(g)')),
                ('volume', models.IntegerField(blank=True, null=True, verbose_name='体积(cm³)')),
                ('variants', models.JSONField(blank=True, null=True, verbose_name='颜色变体')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('protocols', models.ManyToManyField(blank=True, to='products.protocol', verbose_name='支持协议')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ['-created_at'],
            },
        ),
    ]
